1.1/cross library contexts
FirelyTeam/firely-cql-sdk pull request #231
Opened 2024-03-07 17:08 UTC by baseTwo

WIP

2024-03-08 11:01 UTC, ewoutkramer requested changes

2024-03-08 11:01 UTC, ewoutkramer commented on Cql/CodeGeneration.NET/AssemblyCompiler.cs
> +                _libraryExpressionBuilder.ProcessLibrary(libctx);
It's now implicit how built expressions are ending up in `packageDefinitions`, I assume that by passing `packageDefinitions` into the context, and then running `ProcessLibrary` on that context, the expressions are added to the `packageDefinitions`, but is there any way to make that more explicit?

2024-03-08 11:01 UTC, ewoutkramer commented on Cql/CoreTests/ExpressionBuilderTests.cs
> +            var libctx = Factory.LibraryExpressionBuilder.CreateContext(definitions, elmPackage, Ordinal.Unspecified);
The ordinals are passed in for a sequential number in the exception message, but it does pollute the CreateContext function a bit now I think - if you have the name of the offending library in the exception message, do we really need the ordinal number?

2024-03-08 11:01 UTC, ewoutkramer commented on Cql/CoreTests/ExpressionBuilderTests.cs
> +            var definitions = new DefinitionDictionary<LambdaExpression>();
It looks a bit repetitive over the last 4 tests. worth avoiding it here?

2024-03-08 11:02 UTC, ewoutkramer commented
An impressive set of work. I think the separation of concerns between building a package (LibraryExpressionBuilder) and building expressions (ExpressionBuilder) in that package make sense.

2024-03-08 11:03 UTC, baseTwo commented on Cql/CodeGeneration.NET/AssemblyCompiler.cs
> +                _libraryExpressionBuilder.ProcessLibrary(libctx);
I will improve on this in the second continuation of cross library contexts. There will still be some shuffling around of state at the top and library level

2024-03-08 11:06 UTC, baseTwo commented on Cql/CoreTests/ExpressionBuilderTests.cs
> +            var libctx = Factory.LibraryExpressionBuilder.CreateContext(definitions, elmPackage, Ordinal.Unspecified);
It applies on not just libraries, but any element in a list. I could remove this entirely and think about dealing with List elements in another way.

2024-03-08 11:07 UTC, baseTwo commented on Cql/CoreTests/ExpressionBuilderTests.cs
> +            var definitions = new DefinitionDictionary<LambdaExpression>();
I'll rework this

2024-03-08 13:34 UTC, EvanMachusak commented
With regard to:
> PackageCLI was building ELM libraries twice, removed the first pass as it was wasteful. Unfortunately this also means writing out c# and fhir resource files on the fly is no longer possible. This whole process needs some rethink.

The easiest way to think about how this process works is to liken it to the way C and C++ compilation works.  In those languages, you can *compile* a single file at a time.  You must then *link* all of those objects into a final library.

We can build ELM files intoLambdas (or Delegates), and even write their C# source code, by themselves.  You can create a `Library` resource that has attachments of the CQL, the ELM, and the C# source code file.  The C# source won't compile on its own without its dependencies, but that's true of the ELM too - e..g, the Java Engine operates on the ELM files, and therefore needs all dependencies to be able to execute.  The `Library` resource has a `relatedArtifacts` property that we use to identify the dependencies, in much the same way in C you would `#include` the other symbols you need.

What we *can't* do is also include DLLs within the `Library` resources unless we have the entire dependency graph's C# files.

So, what you may want to refactor the PackagerCLI to do is:

First pass: create `Library` resources with CQL, ELM, and C# attachments.
2nd pass: given a dependency graph of `Library` resources, compile all C# files using Rosyln to create assemblies (1 per Library), and add the DLL as an attachment back to each `Library`.

2024-03-12 10:25 UTC, ewoutkramer approved these changes

2024-03-12 10:25 UTC, merged