Fix forward references in ExpressionBuilder
FirelyTeam/firely-cql-sdk pull request #437
Opened 2024-07-31 21:37 UTC by ewoutkramer

Fixes #397.

This PR enables the translation of FunctionRef/ExpressionRef to rely on the ref's `resultTypeSpecifier` instead of having to look the definition up in the DefinitionDictionary. Not using the DefinitionDictionary avoids running into the situation where the ref is a forwards reference whereby the DefinitionDictionary does not yet contain the translated function we want to call.

This PR uses the recent functionality added to LibrarySet to lookup a symbol, and expands this to be able to lookup functions by signature. Given the function name in the FUnctionRef/ExpressionRef, and, in the case of an overload, the signature, we can now lookup any function defined in any library in the LibrarySet, so we can copy over the resultTypeSpecifier.

Filling out this resultTypeSpecifier is now done in a pre-processing step, happening when we are constructing the LibrarySet. The pre-processing step will find all Refs, and then do this:

* Try to find the function by name. If it is not an overload, use the resultTypeSpecifier
* If there is an overload, use the Ref's signature, if available.
* If there is no signature, use the types from the Ref's parameters and match on those.

Otherwise, we cannot find the overload, and we will raise an error. This ensures that after the pre-processor has run, *all* Refs have a resultTypeSpecifier, and we can depend on that fact.

This PR re-uses the OverloadedFunctionDefinition, and there are some updates to the `CanCombine` function to make sure the pre-processor fix and the CanCombine use the same criteria.

2024-08-01 07:26 UTC, baseTwo requested changes

2024-08-01 07:26 UTC, baseTwo commented on Cql/Elm/ElmTreeWalker.cs
> +    internal abstract class BaseElmTreeWalker
This class is significant enough to deserve its own file

2024-08-01 07:26 UTC, baseTwo commented on Cql/Elm/ElmTreeWalker.cs
> +            if (Process(node)) return;
Return on its own line, followed by blank line

2024-08-01 07:26 UTC, baseTwo commented on Cql/Elm/Errors.cs
> +    public string GetMessage() => $"Function {Func.Name}' has a parameter '{Element.name}' without a type specifier.";
Missing ' before {Func.Name}

2024-08-01 07:26 UTC, baseTwo commented on Cql/Elm/Errors.cs
> +    public string GetMessage() => $"Function reference to {Func.name}', and parameter {Index} has no type specifier.";
Missing ' before {Func.name}

2024-08-01 07:26 UTC, baseTwo commented on Cql/Elm/ElmTreeWalker.cs
> +    /// Construct a walker.
It isn't constructing the walker , it _is_ the walker. The description needs to be a more detailed

2024-08-01 07:26 UTC, baseTwo commented on Cql/Elm/ElmTreeWalker.cs
> +    /// <param name="filter">A function that controls whether the walker visits a child property or not.</param>
From the description it mentions a predicate against a property, however, the predicate takes a Type. One would have to assume its the type of the value of the property, but this needs to be more explicitly explained

2024-08-01 07:26 UTC, baseTwo commented on Cql/Cql.Compiler/LibrarySetExpressionBuilderContext.cs
> +                // We should remove this when the compiler is fixed.
What is the issue number for this todo?

2024-08-01 07:26 UTC, baseTwo commented on Cql/Cql.Compiler/ExpressionBuilderContext.StaticHelpers.cs
> +        // funcTypeParameters.Length switch
Commented out code can be removed

2024-08-01 07:26 UTC, baseTwo commented on Cql/Cql.Compiler/AmbiguousOverloadCorrector.cs
> +/// profile names are erased by the compiler. This is a temporary fix that should be
Please include the issue number for this todo

2024-08-01 07:26 UTC, baseTwo commented on Cql/Elm/IDefinitionElement.cs
> +        public override string ToString() => $" {Name} : {resultTypeSpecifier}";
The space before {Name} can be removed. If there was a reason for that space here, its a code smell.

2024-08-01 07:26 UTC, baseTwo commented on Cql/Elm/IDefinitionElement.cs
> +            // TODO: This does not guard against duplicate signatures, like the Create method does.
TODOs need an issue number if it is going to be fixed later

2024-08-01 13:28 UTC, baseTwo approved these changes, later dismissed

2024-08-02 11:56 UTC, EvanMachusak commented
I've identified a small issue where we are creating empty `ExpressionRef` nodes for `Retireve.context` for statements that are in `context Unfiltered` and this is causing exceptions during the preprocessing phase.  I will fix it.

2024-08-02 13:48 UTC, EvanMachusak approved these changes, later dismissed
All tests pass.  All HEDIS passes.

2024-08-05 11:02 UTC, EvanMachusak approved these changes, later dismissed

2024-08-05 11:03 UTC, EvanMachusak approved these changes

2024-08-05 11:15 UTC, merged

2024-08-06 13:23 UTC, baseTwo commented
@EvanMachusak, none of the demo projects are able to rebuild as a result of the additional commits. Could you please have a look? Blocking

2024-08-07 09:27 UTC, baseTwo commented
I'm going to revert the entire previous PR #437. This means the related issues (#397, #410, #442 and #443 ) will be undone and moved back to TODO.

2024-08-19 12:42 UTC, baseTwo commented
@ewoutkramer I tried to duplicate the work into a new PR, but still getting stuck
https://github.com/FirelyTeam/firely-cql-sdk/pull/468