534 bug c member access on casted variable needs additional paranthesis
FirelyTeam/firely-cql-sdk pull request #536
Opened 2024-09-12 14:58 UTC by baseTwo

2024-09-13 09:15 UTC, ewoutkramer submitted a review, later dismissed

2024-09-16 11:02 UTC, ewoutkramer requested changes

2024-09-16 11:02 UTC, ewoutkramer commented on Cql/CodeGeneration.NET/ExpressionToCSharpConverter.cs
> +            if (term.StartsWith('(') && term.EndsWith(')'))
When I tried to restructure this a while ago, this bit me, since an expression like `(expr) opr (expr)` has a beginning and ending bracket, but not in a way that we mean it here, so the precedence of opr in such an expression still matters. Well, if this currently gives the right code, we are somehow not producing these kind of expressions anymore, but it's fragile.

2024-09-16 14:34 UTC, baseTwo reviewed
Looks good enough, but I can't approve 🤡

2024-09-16 14:37 UTC, ewoutkramer approved these changes

2024-09-16 14:44 UTC, merged