580 Rough Public API Prototype
FirelyTeam/firely-cql-sdk pull request #658
Opened 2024-12-16 21:02 UTC by baseTwo

Work for #580

2024-12-17 16:26 UTC, and-hus commented
Just some general thoughts about the considerations, which I am not sure if they are implicitly covered (I haven't checked the code yet...):

I assume that the term "API" covers both: Libraries (nuget packages) to add functionality to larger projects or services and command line tools (e.g. nuget packages installed as a dotnet tools). Where the command line tool is basically a wrapper around the library. I assume that it's planned to create both - right?

Working on files is definitively the most important use case.
But what do you think about an abstraction layer to enable support for different sources or sinks than just files, e.g. a database? It might be worth the effort to add this abstraction layer early on to be prepared for different use cases than just file based actions. This might become handy if you want to used the SDK in a larger project - e.g. integrate it into a FHIR server or another service.

Nice idea to design a fluent interface - I like the approach.
It probably already serves the purpose of the abstraction layer I mentioned above...

One thought about execution of libraries. I think it would be nice to have both options:
- Execute the whole library, so run all expressions and return a dictionary with the results  
  Basically what the `Run()` method in the AssemblyLoadContextExtensions implements
- Execute just a single expression and return just this result  
  So something like `object? asm.RunExpression(library, version, context, expression)`

2024-12-17 16:33 UTC, and-hus commented on Cql/CqlSdkPrototype/Program.cs
> +public readonly record struct ElmVersionedIdentifier
I think this struct is generic enough to be used in other contexts then just for the Elm, e.g. for the FHIR library resources etc. So what do you think about renaming this to just `VersionedIdentifier`?

2024-12-17 16:36 UTC, and-hus commented on Cql/CqlSdkPrototype/Program.cs
> +    public static ElmVersionedIdentifier ParseString(string text)
To be consistend with `FromNameAndVersion()` and `FromVersionedIdentifier()` I would propose to rename this method to `FromString()` - what do you think?

2024-12-18 08:50 UTC, and-hus commented
Regarding the API for the ElmCompiler, what do you think about using the builder pattern, so something along these lines:

```csharp
var elmCompiler = 
          ElmCompilerBuilder
                .New
                .WithInputFile(elmInDir, ElmVersionedIdentifier.FromNameAndVersion("FHIRHelpers"))
                .WithInputFolder(elmInDir, new EnumerationOptions() { RecurseSubdirectories = false })
                .WithCSharpOutputFolder(csharpOutDir)
                .WithAssemblyOutputFolder(dllOutDir)
                .Build();
                
elmCompiler.Compile();
```

2024-12-18 10:00 UTC, baseTwo commented on Cql/CqlSdkPrototype/Program.cs
> +public readonly record struct ElmVersionedIdentifier
There is already a VersionedIdentifier as part of the ELM xml types. I didn't want to change it just yet for the prototype, might do that later

2024-12-18 10:00 UTC, baseTwo commented on Cql/CqlSdkPrototype/Program.cs
> +    public static ElmVersionedIdentifier ParseString(string text)
I changed this to just Parse

2024-12-18 10:03 UTC, baseTwo commented
> Regarding the API for the ElmCompiler, what do you think about using the builder pattern, so something along these lines:
> 
> ```cs
> var elmCompiler = 
>           ElmCompilerBuilder
>                 .New
>                 .WithInputFile(elmInDir, ElmVersionedIdentifier.FromNameAndVersion("FHIRHelpers"))
>                 .WithInputFolder(elmInDir, new EnumerationOptions() { RecurseSubdirectories = false })
>                 .WithCSharpOutputFolder(csharpOutDir)
>                 .WithAssemblyOutputFolder(dllOutDir)
>                 .Build();
>                 
> elmCompiler.Compile();
> ```

I have considered a builder pattern, but I really want to be able to modify the "ElmCompilation" even after compilation. (Think about running this for the Visual Studio plugin which does incremental builds, adding/removing files even after a compile).

We want to be able to add/remove files, compile, and repeat

2025-01-14 11:49 UTC, baseTwo commented
Since this PR size is getting big, I'm splitting up the work into more sub tasks

2025-01-14 16:32 UTC, and-hus commented on Cql/CqlSdkPrototype/Cql/CqlApi.cs
> +    public static CqlApi Create(CqlApiOptions? options = null) => new(options ?? CqlApiOptions.Default);
The class has both, a public primary constructor and this static factory method. 
So there are basically two ways to create an instance of this class - is this intentionally? 
To have just one controlled way for instantiation, I would propose to make the constructor private which leaves the static factory method as the only way to create an instance. What do you think?

2025-01-15 09:57 UTC, and-hus commented on Cql/CqlSdkPrototype/App/Program.cs
> +        // - Should we keep the dependency on Microsoft's ILogger or should we create our own logging abstraction?
Out of curiosity: 
What's the problem with Microsoft's ILogger<> ? 
Why are you considering to create your own logging abstraction? What are you trying to achieve that is not possible with ILogger?

2025-01-15 09:59 UTC, baseTwo commented on Cql/CqlSdkPrototype/App/Program.cs
> +        // - Should we keep the dependency on Microsoft's ILogger or should we create our own logging abstraction?
I use Microsoft's logging framework in the current PR.

2025-01-15 10:00 UTC, baseTwo commented on Cql/CqlSdkPrototype/App/Program.cs
> +        // - Should we keep the dependency on Microsoft's ILogger or should we create our own logging abstraction?
I should move out my thoughts from the code though,. They're all in the parent issue's description  #670

2025-01-15 10:10 UTC, baseTwo commented on Cql/CqlSdkPrototype/App/Program.cs
> +        // - Should we keep the dependency on Microsoft's ILogger or should we create our own logging abstraction?
I am using ILogProvider[] in the LoggingOptions, but I think it should be changed to ILoggerFactory instead.

2025-01-15 10:46 UTC, and-hus commented on Cql/CqlSdkPrototype/App/Program.cs
> +        // - Should we keep the dependency on Microsoft's ILogger or should we create our own logging abstraction?
I agree - I am also more used to `ILogger<>` or `ILoggerFactory`...

From the perspective of a user/consumer of the API, I would expect the API to accept either a `ILogger<TCategoryName>` parameter or an `ILoggerFactory`. So something like

```csharp
 public class CqlApi(){

    public static CqlApi Create(ILogger<CqlApi> logger = null);
 }
```

or

```csharp
 public class CqlApi(){

    public static CqlApi Create(ILoggerFactory loggerFactory = null);
 }
```

See e.g. [here](https://learn.microsoft.com/en-us/dotnet/core/extensions/logging-library-authors) for some guidance on when to use which approach.

But I assume that I'm just not getting the point why the current setup is required  ;-)

2025-01-15 10:52 UTC, baseTwo commented on Cql/CqlSdkPrototype/App/Program.cs
> +        // - Should we keep the dependency on Microsoft's ILogger or should we create our own logging abstraction?
The API's create their own ServiceProvider which will create ILogger for all the internal services required including the API's. When setting up the ServiceProvider, it needs to know how to set up the LoggingBuilder. This is where the LoggingOptions comes in.

2025-01-15 10:56 UTC, baseTwo commented on Cql/CqlSdkPrototype/App/Program.cs
> +        // - Should we keep the dependency on Microsoft's ILogger or should we create our own logging abstraction?
I'm looking now if it's possible to only use ILoggerFactory in LoggingOptions, instead of passing in ILoggerProvider[] and the log filtering delegate.

2025-01-15 11:14 UTC, and-hus commented on Cql/CqlSdkPrototype/App/Program.cs
> +        // - Should we keep the dependency on Microsoft's ILogger or should we create our own logging abstraction?
Yes - I think that would be good and would allow the consumers of the API to use standard Microsoft Logging setups or 3rd party log providers like Serilog which typically provide dependency injection for `ILogger<>` or `ILoggerFactory` - I am not sure how this would work with `ILoggerProvider[]` ...

2025-01-15 11:15 UTC, baseTwo commented on Cql/CqlSdkPrototype/App/Program.cs
> +        // - Should we keep the dependency on Microsoft's ILogger or should we create our own logging abstraction?
Ok, ILoggerFactory was the correct choice. Please see changes in the commit.

2025-01-15 11:21 UTC, baseTwo commented on Cql/CqlSdkPrototype/App/Program.cs
> +        // - Should we keep the dependency on Microsoft's ILogger or should we create our own logging abstraction?
Setting up up logging now looks like this

```csharp
        // This would be set up in the consumers startup logic
        using var serviceProvider =
            new ServiceCollection()
                .AddLogging(lb => lb
                  .ClearProviders()
                  .AddProvider(new ColorConsoleLoggerProvider())
                  .AddFilter((category, _) => category?.Contains(value: nameof(CqlSdkPrototype)) ?? false))
                .BuildServiceProvider();

        // ILoggerFactory would be available through constructor dependency injection, and not directly from IServiceProvider
        var loggingOptions = new LoggingOptions(LoggerFactory: serviceProvider.GetRequiredService<ILoggerFactory>());

        var cqlApiOptions = new CqlApiOptions(
            LoggingOptions: loggingOptions,
            Models: [Models.ElmR1, Models.Fhir401]);

        var cqlApi = new CqlApi(cqlApiOptions);

```

2025-01-20 15:25 UTC, ewoutkramer requested changes

2025-01-20 15:25 UTC, ewoutkramer commented on Cql/CoreTests/PrimitiveTests.cs
> +            Assert.IsTrue(true);
Does this test that the Compile() does not throw? Can we somehow make that more explicit (maybe FluentAssertions DoesNotThrow?)

2025-01-20 15:25 UTC, ewoutkramer commented on Cql/Cql.Abstractions/ISingleton.cs
> +public interface ISingleton
Is this useful?

2025-01-20 15:25 UTC, ewoutkramer commented on Cql/Cql.CqlToElm/Visitors/TimingExpressionVisitor.cs
> +        internal static bool EnableDebugAssertions = true;
Why is this on TimingExpressionVisitor specifically?

2025-01-20 15:25 UTC, ewoutkramer commented on Cql/Cql.Packaging/FhirResourceWriterOptions.cs
> + #1#
Would you not want to delete this file instead of commenting it out completely?

2025-01-20 15:25 UTC, ewoutkramer commented on Cql/Cql.Runtime/EmptyDisposable.cs
> +internal readonly record struct EmptyDisposable : IDisposable
Curious to learn later what you are using this for....

2025-01-20 15:25 UTC, ewoutkramer commented on Cql/CqlSdkPrototype/Cql/CqlApi.cs
> +public class CqlApi :
I am not in love with the name "CqlApi".  Just this morning I confused it with "a library to work with Cql", but it is instead a library to get from Cql to Elm, and the name kind of does not show that. Also, mentioning the term "Api" explicitly feels superfluous. Would CqlToElm or CqlCompiler (well, I guess we have that in the lower-level API already) be something?  CqlConverter, CqlTransformer, CqlProcessor..... CqlSomething ;-)

2025-01-20 15:25 UTC, ewoutkramer commented on Cql/CqlSdkPrototype/Cql/CqlApi.cs
> +    private CqlApiState _state;
I know you initially had CqlApi be read-only, and now it's a big state object in CqlApi, that's almost 1-on-1 with the CqlApi. What was the advantage again of keeping the CqlApi mutable, but the state inside immutable?

2025-01-20 15:25 UTC, ewoutkramer commented on Cql/CqlSdkPrototype/Cql/CqlApiState.cs
> +            _options = value;
With this many side-effects, I'd lean towards `SetOptions()`. Which you probably avoided to be able to use `with`?

2025-01-20 15:25 UTC, ewoutkramer commented on Cql/CqlSdkPrototype/Cql/CqlApiState.cs
> +        ExpressionVisitor.EnableDebugAssertions = false;
I think these were left-over debug statements that we might be able to just remove. But, yes, we'd need to double check with Evan.

2025-01-20 15:25 UTC, ewoutkramer commented on Cql/CqlSdkPrototype/Cql/CqlApiState.cs
> +            ;
I've seen a few empty colons like these, is that on purpose?

2025-01-20 15:25 UTC, ewoutkramer commented on Cql/CqlSdkPrototype/Cql/Extensibility/CqlApiStateEntry.cs
> +public readonly record struct CqlApiStateEntry(CqlLibraryString CqlLibraryString, Library? ElmLibrary = null) {
CqlApiState is internal, does this need to be public?

2025-01-20 15:25 UTC, ewoutkramer commented on Cql/CqlSdkPrototype/Cql/Extensibility/CqlApiStateEntry.cs
> +public readonly record struct CqlApiStateEntry(CqlLibraryString CqlLibraryString, Library? ElmLibrary = null) {
If this is a public facing struct, then we should give it a sexier name, something that says what it is, as the current name is too abstract to tell the user about its function.

2025-01-20 15:25 UTC, ewoutkramer commented on Cql/CqlSdkPrototype/Cql/Internal/ICqlApiInternal.cs
> +internal interface ICqlApiInternal<TCqlApi> : ICqlApiExtendable<TCqlApi>
Maybe explain why there is an internal version with a few lines of comments.

2025-01-20 15:25 UTC, ewoutkramer commented on Cql/CqlSdkPrototype/Elm/ElmApi.cs
> +    public ElmApi(
Same mixed feelings as for "CqlApi".

2025-01-20 15:25 UTC, ewoutkramer commented on Cql/CqlSdkPrototype/Elm/ElmApi.cs
> +    public ElmApi Compile()
That's a big function!

2025-01-20 15:25 UTC, ewoutkramer commented on Cql/CqlSdkPrototype/Elm/ElmApiScopedState.cs
> +internal class ElmApiScopedState(IServiceScope scope) : IDisposable
What are we using scoped state for?

2025-01-20 15:25 UTC, ewoutkramer commented on Cql/CqlSdkPrototype/Elm/ElmApiState.cs
> +            var services = new ServiceCollection();
See CqlApiOptions.Options

2025-01-20 15:25 UTC, ewoutkramer commented on Cql/CqlSdkPrototype/Elm/Extensions/ElmApiExtensions.Cql.cs
> +        return cqlApi
Nice!

2025-01-20 15:25 UTC, ewoutkramer commented on Cql/CqlSdkPrototype/GlobalUsings.cs
> +global using System.Collections.Immutable;
Yeah, add System!

2025-01-20 15:25 UTC, ewoutkramer commented on Cql/CqlSdkPrototype/Infrastructure/CqlLibraryString.cs
> +    [GeneratedRegex("""
Good to have a comment with a reference to where this regex can be found in the CQL documentation here

2025-01-20 15:25 UTC, ewoutkramer commented on Cql/CqlSdkPrototype/Internal/Directories.cs
> +    public static DirectoryInfo AuthoringProjectDirectory => CurrentSolutionDirectory.CreateSubdirectory("Demo").CreateSubdirectory("Measures.Authoring");
It's a bit too much side effect for my taste to create a directory when reading a property, can this property be named GetAuthoringProjectDirectory()?  This applies to the other props here as well of course!

2025-01-20 15:25 UTC, ewoutkramer commented on Cql/CqlSdkPrototype/Internal/InternalExtensions.cs
> +    public static IEnumerable<TR> SelectWhereNotNull<T, TR>(
Would it be far-fetched to have a company-wide library with this stuff? I need it too.  You have done this in your previous job, right?

2025-01-20 15:25 UTC, ewoutkramer commented on Cql/CqlSdkPrototype/Internal/Maybe.cs
> +internal readonly record struct Maybe<T>(T Value)
I have just removed a similar `Result<T>` from the FHIR Plugin. I love the concept, but it's just not common C# enough to have it in the public interface. And I think it will remain a curiosity within your code. Alas, I'd love to use it.

2025-01-20 15:25 UTC, ewoutkramer commented on Cql/CqlSdkPrototype/Logging/ColorConsoleLogger.cs
> +public sealed partial class ColorConsoleLogger(string categoryName, ColorConsoleLoggerProvider provider) : ILogger
Does this need to be public?

2025-01-20 15:25 UTC, ewoutkramer commented on Cql/CqlSdkPrototype/Runtime/Extensions/RuntimeApiExtensions.Cql.cs
> +    public static RuntimeScope CreateRuntimeScope(
As a "new" user, the first question that comes up is: "What's a RuntimeScope and why do I need it?".  When would I call CreateRuntimeScope?

2025-01-20 15:25 UTC, ewoutkramer commented on Cql/CqlSdkPrototype/Runtime/Extensions/RuntimeApiExtensions.RuntimeScope.cs
> +        foreach (var (libId, lib) in scope.Libraries)
Shouldn't this function call `EnumerateLibraryDefinitionsResults` in the foreach, instead of duplicating its code?

2025-01-20 15:25 UTC, ewoutkramer commented on Cql/CqlSdkPrototype/Runtime/Invokers/LibraryInvoker.2_0_8_0.cs
> +        return cqlToolVersion.IsBetween(new Version(2, 0, 8), new Version(2, 1));
Do we make a newer version of this class when the generated libraries change, and in the mean time keep updating the upper boundary for every new release?

2025-01-20 15:25 UTC, ewoutkramer commented on Cql/PackagerCLI/DependencyInjection/PackagerCLiLoggingBuilderExtensions.cs
> +            _ => throw new ArgumentOutOfRangeException(nameof(logLevel), logLevel, "Invalid LogLevel."),
Or use the new standard .NET SwitchExpressionException?

2025-01-20 15:25 UTC, ewoutkramer commented on Demo/Test.Measures.Demo/MeasuresTest.cs
> +        public static RuntimeScope CreateRuntimeScopeFromFhirResourceFile(
What did the RuntimeScope add to AssemblyLoadContext that requires this extra concept of a scope?  (sorry, it's hard to look back in such a big PR into files that I have already reviewed....)

2025-01-20 15:25 UTC, ewoutkramer commented on Demo/Test.Measures.Demo/TestBase.cs
> +    public abstract class TestBase;
Just there to avoid compilation errors?

2025-01-20 15:25 UTC, ewoutkramer commented on Cql/CqlSdkPrototype/Cql/Extensibility/ICqlApiExtendable.cs
> +public interface ICqlApiExtendable<TCqlApi>
What's the advantage of doing this over just writing extensions again the CqlApi class?

2025-01-20 15:25 UTC, ewoutkramer commented on Cql/CqlSdkPrototype/Cql/CqlApi.cs
> +public class CqlApi :
Now that the SDK comes closer to being finzalized, we should enable the check again that all public members need documentation, since there's tons of public members without it now!

2025-01-20 16:33 UTC, baseTwo commented on Cql/CoreTests/PrimitiveTests.cs
> +            Assert.IsTrue(true);
It does throw by default. The options has a flag to set the exception handling. We can write an extension method to make it easier to change, but these convenience methods can come later

2025-01-20 16:34 UTC, baseTwo commented on Cql/Cql.Abstractions/ISingleton.cs
> +public interface ISingleton
I'll remove the non-generic one

2025-01-20 16:35 UTC, baseTwo commented on Cql/Cql.CqlToElm/Visitors/TimingExpressionVisitor.cs
> +        internal static bool EnableDebugAssertions = true;
There are two classes in the cql to elm package that has many debug assertions, of which this type is one. Not sure why asserts were used in the original PR, but i needed a quick way to disable them globally without changing existing behaviour. I suppose these assertions need to be cleaned up. We have to speak to Evan about it, I'll create a note

2025-01-20 16:41 UTC, baseTwo commented on Cql/Cql.Runtime/EmptyDisposable.cs
> +internal readonly record struct EmptyDisposable : IDisposable
Example usage below, shows the use of an IDisposable that might be null based on a condition, but that would not be allowed in a using inline scope. 

```csharp
 using var codeStream = new MemoryStream();
 MemoryStream? pdbStream = debugInformationFormat == AssemblyCompilerDebugInformationFormat.PortablePdb ? new MemoryStream() : null;
 using var pdbStreamDisposable = pdbStream as IDisposable ?? new EmptyDisposable();
```

2025-01-20 16:50 UTC, baseTwo commented on Demo/Test.Measures.Demo/MeasuresTest.cs
> +        public static RuntimeScope CreateRuntimeScopeFromFhirResourceFile(
RuntimeScope encapsulates AssemblyLoadContext, which is disposable, so the RuntimeScope must be disposed when invocation is completed on it, so that the assemblies may unload..

2025-01-20 16:53 UTC, baseTwo commented on Demo/Test.Measures.Demo/TestBase.cs
> +    public abstract class TestBase;
I'll remove the base type, since it no longer contains any class members, and there is only one test that derived from it

2025-01-20 16:54 UTC, baseTwo commented on Cql/CqlSdkPrototype/Cql/CqlApi.cs
> +public class CqlApi :
- #675

2025-01-20 17:15 UTC, baseTwo commented on Cql/CqlSdkPrototype/Cql/Extensibility/ICqlApiExtendable.cs
> +public interface ICqlApiExtendable<TCqlApi>
At the moment no advantage, because there is no derived type on CqlApi. I have already thought of another way to do the fluent style as discussed

2025-01-20 17:16 UTC, baseTwo commented on Cql/Cql.Packaging/FhirResourceWriterOptions.cs
> + #1#
I want to keep this logic readily available when I'm writing the PackagerAPI. After that I'll deleted it before all goes back into the main branch

2025-01-20 17:25 UTC, baseTwo commented on Cql/CqlSdkPrototype/Cql/CqlApi.cs
> +public class CqlApi :
I agree, but I couldn't come up with a good name yet. Ideas? My thoughts around keeping the name general is that, the instance CqlApi or ElmApi serves as the starting point of what you want to do, not what you want to do. That's because there are many extension methods on it that makes it convenient to go through all the stages of the pipeline and produce output.

2025-01-20 17:28 UTC, baseTwo commented on Cql/CqlSdkPrototype/Cql/CqlApi.cs
> +    private CqlApiState _state;
In functional programming, the data object should only contain the data, and external to it, a function will create a new state object. In this case, those functions are in the API type, and the extension methods to the API type

2025-01-20 17:29 UTC, baseTwo commented on Cql/CqlSdkPrototype/Cql/CqlApiState.cs
> +        ExpressionVisitor.EnableDebugAssertions = false;
To be cleaned up in  #674

2025-01-20 17:30 UTC, baseTwo commented on Cql/CqlSdkPrototype/Cql/CqlApiState.cs
> +            ;
Not on purpose, will remove

2025-01-20 17:45 UTC, baseTwo commented on Cql/CqlSdkPrototype/Elm/ElmApiScopedState.cs
> +internal class ElmApiScopedState(IServiceScope scope) : IDisposable
Encapsulates the service provider scope and to get access to the scoped services

2025-01-20 17:46 UTC, baseTwo commented on Cql/CqlSdkPrototype/Elm/ElmApiScopedState.cs
> +internal class ElmApiScopedState(IServiceScope scope) : IDisposable
I want to remove all scoped services during cleanup

2025-01-20 17:48 UTC, baseTwo commented on Cql/CqlSdkPrototype/Elm/Extensions/ElmApiExtensions.Cql.cs
> +        return cqlApi
That's why the name CqlApi or ElmApi needs to have a general name that it is the starting point of the pipeline.

2025-01-20 17:48 UTC, baseTwo commented on Cql/CqlSdkPrototype/GlobalUsings.cs
> +global using System.Collections.Immutable;
I'll add all the System and Microsoft namespaces there as a cleanup task

2025-01-20 17:51 UTC, baseTwo commented on Cql/CqlSdkPrototype/Internal/Directories.cs
> +    public static DirectoryInfo AuthoringProjectDirectory => CurrentSolutionDirectory.CreateSubdirectory("Demo").CreateSubdirectory("Measures.Authoring");
This is only a temporary class used in the cql prototype, not meant for production.

2025-01-20 17:54 UTC, baseTwo commented on Cql/CqlSdkPrototype/Internal/InternalExtensions.cs
> +    public static IEnumerable<TR> SelectWhereNotNull<T, TR>(
These extensions have a tendency to explode in size, bloating the shared libraries. Speaking from experience from previous job :)

2025-01-20 17:55 UTC, baseTwo commented on Cql/CqlSdkPrototype/Internal/Maybe.cs
> +internal readonly record struct Maybe<T>(T Value)
I use it in the Firely CQL SDK too. I hope Microsoft brings a more formal set of monad types into the framework

2025-01-20 17:56 UTC, baseTwo commented on Cql/CqlSdkPrototype/Logging/ColorConsoleLogger.cs
> +public sealed partial class ColorConsoleLogger(string categoryName, ColorConsoleLoggerProvider provider) : ILogger
No, it will be moved to the PackagerCLI project after the CqlSdkPrototype is removed.

2025-01-20 17:58 UTC, baseTwo commented on Cql/CqlSdkPrototype/Runtime/Invokers/LibraryInvoker.2_0_8_0.cs
> +        return cqlToolVersion.IsBetween(new Version(2, 0, 8), new Version(2, 1));
Actually, there should be no upper boundary. When developing a new library format, and the unit tests break, a new invoker must be written on the new version.

2025-01-21 07:33 UTC, baseTwo commented on Cql/Cql.Runtime/EmptyDisposable.cs
> +internal readonly record struct EmptyDisposable : IDisposable
I'll remove this, I thought it wasn't possible to do a `using var disposable = a null IDisposable instance`, but that is indeed possible

2025-01-21 07:51 UTC, baseTwo commented on Cql/CqlSdkPrototype/Elm/ElmApi.cs
> +    public ElmApi Compile()
I split it up into smaller ones

2025-01-21 08:18 UTC, ewoutkramer commented on Cql/CoreTests/PrimitiveTests.cs
> +            Assert.IsTrue(true);
I mean, Assert.IsTrue(true) is obviously always passing, so what is the test testing? Could you add something about the expectation in a comment above this assert.true(true), so later developers understand what this is testing?

2025-01-21 08:22 UTC, ewoutkramer commented on Cql/CqlSdkPrototype/Cql/CqlApi.cs
> +    private CqlApiState _state;
Is there any distinction left between CqlApi and its state now? Is it worth keeping two objects?

2025-01-21 08:23 UTC, ewoutkramer commented on Cql/CqlSdkPrototype/Elm/ElmApi.cs
> +    public ElmApi(
I'll close this discussion. If we find something more appropriate for CqlApi, we can apply that here too.

2025-01-21 08:25 UTC, ewoutkramer commented on Cql/CqlSdkPrototype/Internal/InternalExtensions.cs
> +    public static IEnumerable<TR> SelectWhereNotNull<T, TR>(
I'm just jealous I guess. I am afraid you are right based on experiences we had at Furore. I had slight hopes you fared better ;-)

2025-01-21 08:26 UTC, ewoutkramer commented on Cql/CqlSdkPrototype/Internal/Maybe.cs
> +internal readonly record struct Maybe<T>(T Value)
Yeah, but until that moment, I don't think we should introduce a variant in our pubic surface and stick to the current Microsoft designs.

2025-01-21 08:26 UTC, ewoutkramer commented on Cql/CqlSdkPrototype/Runtime/Extensions/RuntimeApiExtensions.Cql.cs
> +    public static RuntimeScope CreateRuntimeScope(
So, you want to remove all scopes in a future PR, closing this discussion.

2025-01-21 08:28 UTC, ewoutkramer commented on Cql/CqlSdkPrototype/Runtime/Invokers/LibraryInvoker.2_0_8_0.cs
> +        return cqlToolVersion.IsBetween(new Version(2, 0, 8), new Version(2, 1));
You mean to say that the IsBeween (with upper boundary Version(2,1)) should be removed from this code?

2025-01-21 08:29 UTC, ewoutkramer commented on Demo/Test.Measures.Demo/MeasuresTest.cs
> +        public static RuntimeScope CreateRuntimeScopeFromFhirResourceFile(
Yes, so they are both disposable, but what does the wrapper introduce that the AssemblyLoadContext does not have?

2025-01-21 08:40 UTC, baseTwo commented on Cql/CqlSdkPrototype/Runtime/Invokers/LibraryInvoker.2_0_8_0.cs
> +        return cqlToolVersion.IsBetween(new Version(2, 0, 8), new Version(2, 1));
Yes, the upper bound is removed now. If we follow semantic versioning on the code generated part, then it would be easy to put an upper limit on the version major part, but the versioning of the code generated libraries is tied to the SDK version itself. That relationship needs to be broken up

2025-01-21 09:42 UTC, baseTwo commented on Cql/CqlSdkPrototype/Cql/CqlApiState.cs
> +            _options = value;
Have a look at the latest commit. I split up options, entries and services as separate fields on the cqlapi. I'll do elmapi later

2025-01-21 12:08 UTC, baseTwo commented on Cql/CoreTests/PrimitiveTests.cs
> +            Assert.IsTrue(true);
Improve the assertion

2025-01-21 12:26 UTC, baseTwo commented on Cql/CqlSdkPrototype/Internal/Maybe.cs
> +internal readonly record struct Maybe<T>(T Value)
Internal, wont go public

2025-01-21 12:41 UTC, baseTwo commented on Demo/Test.Measures.Demo/MeasuresTest.cs
> +        public static RuntimeScope CreateRuntimeScopeFromFhirResourceFile(
Will rename to LibrarySetInvoker etc #697

2025-01-21 12:45 UTC, baseTwo commented on Cql/CqlSdkPrototype/Runtime/Invokers/LibraryInvoker.2_0_8_0.cs
> +        return cqlToolVersion.IsBetween(new Version(2, 0, 8), new Version(2, 1));
- #698

2025-01-21 12:46 UTC, ewoutkramer approved these changes
All open issues discussed, many will be handled in another PR to not make merging harder.

2025-01-21 12:46 UTC, merged

2025-01-21 13:44 UTC, baseTwo commented on Cql/CoreTests/PrimitiveTests.cs
> +            Assert.IsTrue(true);
Fixed