feat: Expose TypeResolver, CqlCrosswalk, and TypeConverter publicly
FirelyTeam/firely-cql-sdk pull request #84
Opened 2023-10-12 17:12 UTC by patburke234

At NCQA, our existing DCS software utilizes the TypeResolver and TypeConverter classes. We use these to convert between the CQL and FHIR data models in various parts of our application. This PR is to expose the minimum set of classes/methods that we need publicly.

@ewoutkramer - seems my last change reverted my first change accidentally. I messed something up with Git. Here are all the same changes from #80  but with the changes you requested in the original PR.

2023-10-13 08:02 UTC, ewoutkramer requested changes
@patburke234 - just a few more questions, before we make this type public for ever ;-)

2023-10-13 08:02 UTC, ewoutkramer commented on Cql/Cql.Packaging/CqlCrosswalk.cs
> +    public record TypeEntry(
Is this then a `CqlTypeToFhirMapping` ?

2023-10-13 17:52 UTC, patburke234 commented on Cql/Cql.Packaging/CqlCrosswalk.cs
> +    public class CqlCrosswalk
Sure, that's a good summary. It can map between those types in both directions.

2023-10-13 17:52 UTC, patburke234 commented on Cql/Cql.Packaging/CqlCrosswalk.cs
> +    public record TypeEntry(
Yes, that's accurate. Can update these.

2023-10-16 07:44 UTC, ewoutkramer approved these changes

2023-10-16 07:44 UTC, merged